version: '3'

services:
    codexchange:
      container_name: codexchange
      build: .
      restart: unless-stopped
      ports:
          - 80:80
      volumes:
      - .:/app

    mysql_db:
      image: mysql:latest
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: cx
        MYSQL_DATABASE: codexchange
        MYSQL_USER: cx
        MYSQL_PASSWORD: cx
      ports:
      - 3306:3306
