version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: codexchange_app
    container_name: codexchange_app
    ports:
      - "8001:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: codexchange_mysql
    ports:
      - "8306:3306"
    environment:
      MYSQL_DATABASE: codexchange
      MYSQL_ROOT_PASSWORD: cx
      MYSQL_USER: cx
      MYSQL_PASSWORD: cx
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
